### ISSUE TITLE
Step 3 Error 

### ISSUE THREAD

**Issue by im-noob** [dedshit/Zee5#16]
Error Received in 3rd step... 

```require 'Zee5'```

Traceback (most recent call last):
	2: from zee.rb:2:in `<main>'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- Zee5 (LoadError)
	3: from zee.rb:2:in `<main>'
	2: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:156:in `require'
	1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `rescue in require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:168:in `require': cannot load such file -- Zee5 (LoadError)

**Comment by dedshit** [comment]
Did you install gem file ?

**Comment by dedshit** [comment]
![20201204_084605](https://user-images.githubusercontent.com/62318734/101117595-509eef00-360d-11eb-9a7c-09d99f7a22b5.jpg)

**Comment by im-noob** [comment]
> Did you install gem file?

Yes, I did... 
Checkout the Snap shot...

![image](https://user-images.githubusercontent.com/32417365/101243969-af598b00-3729-11eb-8a8f-67b7b5e2c97f.png)

**Comment by dELUSION-MS** [comment]
I think I also have same problem!!

```
irb(main):001:0> require 'Zee5'
Traceback (most recent call last):
        6: from /usr/bin/irb:23:in `<main>'
        5: from /usr/bin/irb:23:in `load'
        4: from /usr/lib/ruby/gems/2.7.0/gems/irb-1.2.1/exe/irb:11:in `<top (required)>'
        3: from (irb):1
        2: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
        1: from /usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
LoadError (cannot load such file -- Zee5)
```

**Comment by dedshit** [comment]
sry its obsolete
